### ISSUE TITLE
How to set the merchant's account to receive the payment?

### ISSUE THREAD

**Issue by imkhairulikhwan** [paypal/rest-api-sample-app-dotnet#8]
Hello and good day, 

I am sorry, but i am kind of new developer so I am not too sure, after customer putting in their credit card details, and make payment, I can see it will re-direct us to the sandbox paypal account. But how do I change this account to my account? 

Also if the customer select the payment as credit card and make payment, I am not sure how do I set the payment to go to my account. 

Thank you in advance

**Comment by jziaja** [comment]
Hi @imkhairulikhwan, these samples are unfortunately a bit out-of-date.  I'd recommend taking a look at the [samples included with the **PayPal .NET SDK**](https://github.com/paypal/PayPal-NET-SDK/wiki/Samples).  Specifically, the samples on making payments with a [credit card](https://github.com/paypal/PayPal-NET-SDK/blob/master/Samples/Source/PaymentWithCreditCard.aspx.cs), [stored credit card](https://github.com/paypal/PayPal-NET-SDK/blob/master/Samples/Source/PaymentWithSavedCard.aspx.cs), or [PayPal account](https://github.com/paypal/PayPal-NET-SDK/blob/master/Samples/Source/PaymentWithPayPal.aspx.cs) should help you out with what you're trying to do.

I'd also recommend reading up on the [developer docs for making payments](https://developer.paypal.com/docs/integration/direct/rest-payments-overview/).  They help to go over the flow for both a [PayPal payment](https://developer.paypal.com/docs/integration/web/accept-paypal-payment/) and a [credit card payment](https://developer.paypal.com/docs/integration/direct/accept-credit-cards/).  The main difference between the two flows is a PayPal payment (`payment.payer.payment_method = "paypal"`) must be executed after the buyer has approved the payment using their PayPal account.  A credit card payment (`payment.payer.payment_method = "credit_card"`) does not require execution of the payment resource.

If you have any further questions or need help getting your code to work, let me know and I'd be more than happy to help you out.

Also, if any of your questions are specifically about using the SDK, please open an issue over on the [PayPal .NET SDK](https://github.com/paypal/PayPal-NET-SDK) repo.
