### ISSUE TITLE
Invalid HTTP response

### ISSUE THREAD

**Issue by riccainfo** [paypal/rest-api-sample-app-dotnet#9]
Hello,

I'm using 'PizzaApp.VS.2008' solution with Visual Studio 2015.
After sign up, I get this message:

Error Message:Invalid HTTP response Connessione sottostante chiusa: Errore imprevisto durante un'operazione di invio

How can I fix it?

**Comment by pp-randy** [comment]
I apologize for the delay in response.

You are probably facing TLS issues more here: https://github.com/paypal/tls-update#net

I suggest trying these samples here: https://github.com/paypal/PayPal-NET-SDK/tree/develop/Samples
